### PR TITLE
added circle tests

### PR DESCRIPTION
**Pull request by MeirShpilraien**

### CODE REVIEW

**Comment by MeirShpilraien** [comment]
https://github.com/RedisGears/redisgears-py/issues/8

**Review by rafie — COMMENTED** [review]
Are you sure you'd like to remove `early_return_for_forked_pull_requests`? We can try creating a forked PR and see if it breaks.

**Comment by MeirShpilraien** [comment]
@rafie shouldn't it just work?
I just saw that we do not have it on RGSYNC so I removed it. I can take it back...

**Comment by rafie** [comment]
@MeirShpilraien We had something similar in TimeSeries this week. CircleCI will not export environment variables to forked PRs in order not to expose secrets. In our modules, only Graph is implementing the early return. Let's try to go without it, and if it breaks, we put it back. I try to keep the config.yml files short and concise, but they manage to grow wild nevertheless.

**Review by rafie — APPROVED** [review]

**Pull request merged**
